name: Build
run-name: build

on: [push]

jobs:
  build:
    runs-on: 
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc main.c src/*.c -I include/ -o executable
      - uses: actions/upload-artifact@v3
        with:
          name: executable-linux
          path: executable
          retention-days: 90